import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getInterviewReport } from '../../services/api';
import { Download, Share2, Shield, CheckCircle, AlertCircle, FileText, ChevronLeft } from 'lucide-react';

export default function InterviewReport() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchReport = async () => {
            try {
                const res = await getInterviewReport(id);
                setReport(res.data.report);
            } catch (err) {
                console.error('Error fetching report:', err);
                setError('Failed to load candidate report.');
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-gray-50">
                <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-indigo-600"></div>
            </div>
        );
    }

    if (error || !report) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 p-4">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">Error</h2>
                <p className="text-gray-600 mb-6">{error || 'Report not found'}</p>
                <button onClick={() => navigate('/dashboard')} className="text-indigo-600 font-medium hover:underline">Back to Dashboard</button>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-50 font-sans text-gray-900 pb-24">
            {/* Header */}
            <div className="bg-white border-b border-gray-200 sticky top-0 z-20 shadow-sm">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <button onClick={() => navigate('/dashboard')} className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition">
                            <ChevronLeft size={20} />
                        </button>
                        <div>
                            <h1 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                                <FileText size={16} className="text-gray-400" />
                                Candidate Report
                            </h1>
                            <p className="text-xs text-gray-500">Generated by Talento AI • {new Date(report.completedAt).toLocaleDateString()}</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button onClick={() => window.print()} className="flex items-center gap-2 px-4 py-2 text-xs font-bold text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition shadow-sm">
                            <Download size={14} /> Download PDF
                        </button>
                    </div>
                </div>
            </div>

            {/* Paper */}
            <div className="max-w-[850px] mx-auto mt-8 sm:mt-12 bg-white sm:rounded-xl shadow-xl min-h-[800px] relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-500"></div>

                <div className="p-8 sm:p-16">
                    {/* Status Overview */}
                    <div className="flex flex-col sm:flex-row justify-between items-start border-b-2 border-gray-100 pb-8 mb-12">
                        <div>
                            <h1 className="text-3xl font-bold text-gray-900 mb-1">{report.candidateName}</h1>
                            <p className="text-lg text-gray-500 font-medium">{report.jobTitle}</p>
                            <p className="text-sm text-gray-400 mt-2">{report.candidateEmail}</p>
                        </div>
                        <div className="mt-6 sm:mt-0 flex items-center gap-4">
                            <div className="text-right">
                                <p className="text-xs uppercase tracking-widest font-bold text-gray-400 mb-1">Confidence Score</p>
                                <p className="text-4xl font-black text-emerald-600">{report.aiAnalysis?.confidenceScore || 0}%</p>
                            </div>
                            <div className="w-16 h-16 rounded-full border-4 border-emerald-100 flex items-center justify-center bg-emerald-50">
                                <Shield className="w-8 h-8 text-emerald-600" />
                            </div>
                        </div>
                    </div>

                    {/* Executive Summary */}
                    <div className="mb-12">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4">Executive Summary</h3>
                        <div className="p-6 bg-gray-50 rounded-xl border border-gray-100 text-gray-700 leading-relaxed text-sm text-justify">
                            {report.aiAnalysis?.summary || 'No summary available.'}
                        </div>
                    </div>

                    {/* Breakdown Grid */}
                    <div className="grid md:grid-cols-2 gap-12 mb-12">
                        <div>
                            <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-emerald-700 mb-6 pb-2 border-b border-gray-100">
                                <CheckCircle size={16} /> Key Strengths
                            </h3>
                            <ul className="space-y-4">
                                {report.aiAnalysis?.strengths?.map((str, i) => (
                                    <li key={i} className="flex gap-3 text-sm text-gray-700">
                                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0"></div>
                                        <span className="leading-relaxed">{str}</span>
                                    </li>
                                ))}
                                {(!report.aiAnalysis?.strengths || report.aiAnalysis.strengths.length === 0) && (
                                    <li className="text-sm text-gray-400">None identified.</li>
                                )}
                            </ul>
                        </div>
                        <div>
                            <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-amber-600 mb-6 pb-2 border-b border-gray-100">
                                <AlertCircle size={16} /> Concerns/Improvements
                            </h3>
                            <ul className="space-y-4">
                                {report.aiAnalysis?.concerns?.map((con, i) => (
                                    <li key={i} className="flex gap-3 text-sm text-gray-700">
                                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0"></div>
                                        <span className="leading-relaxed">{con}</span>
                                    </li>
                                ))}
                                {(!report.aiAnalysis?.concerns || report.aiAnalysis.concerns.length === 0) && (
                                    <li className="text-sm text-gray-400">None identified.</li>
                                )}
                            </ul>
                        </div>
                    </div>

                    {/* Technical Keywords */}
                    <div className="mb-12">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-6">Keywords Detected</h3>
                        <div className="flex flex-wrap gap-2">
                            {report.aiAnalysis?.keywordAnalysis?.map((kw, i) => (
                                <span key={i} className="px-3 py-1.5 bg-indigo-50 border border-indigo-100 rounded-lg text-xs font-bold text-indigo-700">
                                    {kw}
                                </span>
                            ))}
                        </div>
                    </div>
                    
                    {/* Final Recommendation */}
                    <div className="mb-12 p-6 bg-indigo-900 rounded-xl text-white">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-indigo-300 mb-2">Final Recommendation</h3>
                        <p className="text-lg font-medium">{report.aiAnalysis?.recommendation || 'Needs Manual Review'}</p>
                    </div>

                    {/* Raw QA Section */}
                    {report.questions && report.answers && (
                        <div className="mt-16 pt-8 border-t border-gray-200">
                            <h3 className="text-xl font-bold text-gray-900 mb-8">Raw Interview Transcript</h3>
                            <div className="space-y-10">
                                {report.questions.map((q, idx) => {
                                    const ans = report.answers[idx];
                                    return (
                                        <div key={idx} className="bg-gray-50 p-6 rounded-xl border border-gray-100">
                                            <p className="text-sm font-bold text-indigo-600 mb-3 uppercase tracking-wider">Question {idx + 1}</p>
                                            <p className="text-lg text-gray-900 font-medium mb-6">{q.question}</p>
                                            
                                            <div className="bg-white p-5 rounded-lg border border-gray-200 relative">
                                                <div className="absolute -top-3 left-4 bg-gray-200 text-gray-600 text-[10px] font-bold px-2 py-0.5 rounded uppercase">Candidate Answer</div>
                                                <p className="text-gray-700 text-sm leading-relaxed whitespace-pre-wrap">{ans ? ans.answer : 'No answer recorded.'}</p>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
