import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getSampleReport } from '../../services/api';
import {
    Download, Share2, Shield, Calendar, Clock,
    CheckCircle, AlertCircle, FileText, ChevronLeft, ChevronRight
} from 'lucide-react';

export default function SampleReport() {
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const navigate = useNavigate();

    useEffect(() => {
        const fetchReport = async () => {
            // Mock data fallback
            const mockReport = {
                candidateName: 'Alex Morgan',
                jobTitle: 'Senior Full Stack Engineer',
                completedAt: new Date().toISOString(),
                aiAnalysis: {
                    confidenceScore: 92,
                    summary: "Alex demonstrates exceptional command of modern web technologies. Their explanation of distributed system design patterns was particularly impressive, showing deep understanding of scalability trade-offs. Communication is clear, concise, and technical.",
                    strengths: [
                        "Deep understanding of React concurrency and state management",
                        "Design system architecture experience",
                        "Strong grasp of database normalization vs denormalization",
                        "Excellent communication of complex technical concepts"
                    ],
                    concerns: [
                        "Limited hands-on experience with Kubernetes",
                        "Could improve initial estimation accuracy"
                    ],
                    keywordAnalysis: ['React', 'Node.js', 'System Design', 'Redis', 'PostgreSQL', 'AWS', 'TypeScript', 'Docker']
                }
            };

            try {
                const res = await getSampleReport();
                if (res.data && res.data.report) {
                    setReport(res.data.report);
                } else {
                    setReport(mockReport);
                }
            } catch (error) {
                console.error('Error fetching sample report, using fallback:', error);
                setReport(mockReport);
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, []);

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-secondary-50">
                <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-indigo-600"></div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-secondary-50 font-sans text-secondary-900 pb-24">
            {/* Context Header */}
            <div className="bg-white border-b border-secondary-200 sticky top-0 z-20 shadow-sm">
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <button onClick={() => navigate('/')} className="p-2 hover:bg-secondary-50 rounded-full text-secondary-500 transition">
                            <ChevronLeft size={20} />
                        </button>
                        <div>
                            <h1 className="text-sm font-bold text-secondary-900 flex items-center gap-2">
                                <FileText size={16} className="text-secondary-400" />
                                Candidate Report
                            </h1>
                            <p className="text-xs text-secondary-500">Generated by Talento AI • {new Date(report?.completedAt).toLocaleDateString()}</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button className="hidden sm:flex items-center gap-2 px-3 py-1.5 text-xs font-medium text-secondary-600 bg-secondary-50 border border-secondary-200 rounded-md hover:bg-secondary-100 transition">
                            <Share2 size={14} /> Share
                        </button>
                        <button className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-white bg-indigo-600 rounded-md hover:bg-indigo-700 transition shadow-sm">
                            <Download size={14} /> Download PDF
                        </button>
                    </div>
                </div>
            </div>

            {/* Main Report "Paper" */}
            <div className="max-w-[850px] mx-auto mt-8 sm:mt-12 bg-white sm:rounded-none sm:rounded-t-sm shadow-xl min-h-[1100px] relative">
                {/* Top Decorator Line */}
                <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-500"></div>

                <div className="p-8 sm:p-16">
                    {/* Report Header */}
                    <div className="flex flex-col sm:flex-row justify-between items-start border-b-2 border-secondary-100 pb-8 mb-12">
                        <div>
                            <h1 className="text-3xl font-display font-bold text-secondary-900 mb-1">{report?.candidateName}</h1>
                            <p className="text-lg text-secondary-500 font-medium">{report?.jobTitle}</p>
                        </div>
                        <div className="mt-6 sm:mt-0 flex items-center gap-4">
                            <div className="text-right">
                                <p className="text-xs uppercase tracking-widest font-bold text-secondary-400 mb-1">Confidence</p>
                                <p className="text-3xl font-bold text-emerald-600">{report?.aiAnalysis?.confidenceScore}%</p>
                            </div>
                            <div className="w-16 h-16 rounded-full border-4 border-emerald-100 flex items-center justify-center">
                                <Shield className="w-8 h-8 text-emerald-600" />
                            </div>
                        </div>
                    </div>

                    {/* Executive Summary */}
                    <div className="mb-12">
                        <h3 className="text-sm font-bold uppercase tracking-widest text-secondary-400 mb-4">Executive Summary</h3>
                        <div className="p-6 bg-secondary-50 rounded-xl border border-secondary-100 text-secondary-700 leading-relaxed text-sm text-justify">
                            {report?.aiAnalysis?.summary}
                        </div>
                    </div>

                    {/* Breakdown Grid */}
                    <div className="grid md:grid-cols-2 gap-12 mb-12">
                        <div>
                            <h3 className="flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-emerald-700 mb-6 pb-2 border-b border-secondary-100">
                                <CheckCircle size={16} /> Key Strengths
                            </h3>
                            <ul className="space-y-4">
                                {report?.aiAnalysis?.strengths.map((str, i) => (
                                    <li key={i} className="flex gap-3 text-sm text-secondary-700">
                                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0"></div>
                                        <span className="leading-relaxed">{str}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <div>
                            <h3 className="flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-amber-600 mb-6 pb-2 border-b border-secondary-100">
                                <AlertCircle size={16} /> Improvements
                            </h3>
                            <ul className="space-y-4">
                                {report?.aiAnalysis?.concerns.map((con, i) => (
                                    <li key={i} className="flex gap-3 text-sm text-secondary-700">
                                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0"></div>
                                        <span className="leading-relaxed">{con}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>

                    {/* Technical Skills Map */}
                    <div className="mb-12">
                        <h3 className="text-sm font-bold uppercase tracking-widest text-secondary-400 mb-6">Technical Competencies</h3>
                        <div className="flex flex-wrap gap-2">
                            {report?.aiAnalysis?.keywordAnalysis.map((kw, i) => (
                                <span key={i} className="px-3 py-1.5 bg-white border border-secondary-200 rounded-md text-xs font-medium text-secondary-600 shadow-sm">
                                    {kw}
                                </span>
                            ))}
                            {['System Design', 'API Architecture', 'React Performance', 'CI/CD Pipelines'].map((kw, i) => (
                                <span key={`extra-${i}`} className="px-3 py-1.5 bg-white border border-secondary-200 rounded-md text-xs font-medium text-secondary-600 shadow-sm">
                                    {kw}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Footer Watermark */}
                    <div className="mt-24 pt-8 border-t border-secondary-100 flex justify-between items-center opacity-40 hover:opacity-100 transition-opacity">
                        <div className="flex items-center gap-2">
                            <div className="w-5 h-5 bg-secondary-900 rounded-md"></div>
                            <span className="font-bold text-secondary-900 text-sm">Talento Verify</span>
                        </div>
                        <p className="text-xs text-secondary-500">Report ID: {report?._id || 'SAMPLE-X92-J88'}</p>
                    </div>
                </div>
            </div>

            {/* Bottom CTA Overlay */}
            <div className="fixed bottom-8 left-1/2 -translate-x-1/2 z-30">
                <button
                    onClick={() => navigate('/signup')}
                    className="flex items-center gap-2 px-6 py-3 bg-secondary-900 text-white rounded-full shadow-2xl hover:scale-105 transition-transform font-bold text-sm"
                >
                    Generate full report <ChevronRight size={16} />
                </button>
            </div>
        </div>
    );
}
